(()=>{
'use strict';
const $=s=>document.querySelector(s),root=$('#samiLaunch'),canvas=$('#samiCinema'),ctx=canvas?.getContext('2d',{alpha:false,desynchronized:true}),gate=$('#launchStartGate'),brand=$('#brandResolve'),logo=$('#finalWordmark'),wordmarkStage=$('#wordmarkStage'),welcomeUI=$('.welcome-ui'),words=$('#pitchWords'),sentence=$('#pitchLine'),status=$('#audioStatus');
const welcomeAudio=$('#welcomeAudio'),salesAudio=$('#salesAudio');
const PROCESS=['SITE VISITS','PHOTOGRAPHS','NOTES','SERVICE INFORMATION','UTILITY PLANS','MEASUREMENTS','VERIFICATION','COMMUNICATION','DRAFTING','CAD','REVIEW','AMENDMENT','RE-REVIEW','APPROVAL','PROJECT CHANGE','UPDATES','TIME','COST','TRAVEL','DUPLICATION','ENVIRONMENTAL IMPACT'];
let mode='welcome',running=false,start=0,raf=0,w=0,h=0,dpr=1,sound=true,cracks=[],blocks=[],cad=[],sparks=[],seed=170926,suspendedAt=0;
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x)),lerp=(a,b,t)=>a+(b-a)*t,out=t=>1-Math.pow(1-clamp(t),3),smooth=t=>{t=clamp(t);return t*t*(3-2*t)},ease=t=>{t=clamp(t);return t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2};
const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
function resize(){if(!ctx)return;const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,1.75);w=r.width;h=r.height;canvas.width=Math.max(1,Math.round(w*dpr));canvas.height=Math.max(1,Math.round(h*dpr));ctx.setTransform(dpr,0,0,dpr,0,0);if(!running)drawStill();}
function vsub(a,b){return a.map((x,i)=>x-b[i])}function dot(a,b){return a.reduce((s,x,i)=>s+x*b[i],0)}function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}function norm(a){const m=Math.hypot(...a)||1;return a.map(x=>x/m)}
function camera(pos,target,fov=54){const forward=norm(vsub(target,pos)),right=norm(cross(forward,[0,1,0])),up=cross(right,forward),f=Math.min(w,h)*.92/Math.tan(fov*Math.PI/360);return{pos,target,forward,right,up,f}}
function project(cam,p){const d=vsub(p,cam.pos),z=dot(d,cam.forward);if(z<=.05)return null;return{x:w/2+dot(d,cam.right)*cam.f/z,y:h/2-dot(d,cam.up)*cam.f/z,z,scale:cam.f/z}}
function path(points){if(points.length<2)return false;ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(let i=1;i<points.length;i++)ctx.lineTo(points[i].x,points[i].y);return true}
function prepareGeometry(){seed=170926;cracks=[];blocks=[];cad=[];sparks=[];const spokes=18;for(let i=0;i<spokes;i++){let a=i/spokes*Math.PI*2+(rnd()-.5)*.18,x=0,z=0,pts=[[0,0,0]],steps=13+Math.floor(rnd()*8);for(let j=0;j<steps;j++){const burst=j<3?.22+rnd()*.17:.42+rnd()*.72;a+=(rnd()-.5)*(.34+j*.014);x+=Math.cos(a)*burst;z+=Math.sin(a)*burst;pts.push([x,.012,z]);if(j>1&&j<steps-1&&rnd()>.52){let bx=x,bz=z,ba=a+(rnd()>.5?1:-1)*(.38+rnd()*.88),branch=[[x,.014,z]],branchSteps=3+Math.floor(rnd()*5);for(let k=0;k<branchSteps;k++){const bl=.19+rnd()*.48;ba+=(rnd()-.5)*(.46+k*.025);bx+=Math.cos(ba)*bl;bz+=Math.sin(ba)*bl;branch.push([bx,.015,bz]);if(k>1&&rnd()>.72){let sx=bx,sz=bz,sa=ba+(rnd()>.5?1:-1)*(.45+rnd()*.55),split=[[bx,.016,bz]];for(let m=0;m<2+Math.floor(rnd()*3);m++){const sl=.15+rnd()*.32;sa+=(rnd()-.5)*.5;sx+=Math.cos(sa)*sl;sz+=Math.sin(sa)*sl;split.push([sx,.016,sz])}cracks.push({pts:split,seed:i*701+j*17+k,branch:true,delay:.18+j*.032+k*.015+rnd()*.12})}}cracks.push({pts:branch,seed:i*101+j,branch:true,delay:.10+j*.032+rnd()*.16})}}cracks.push({pts,seed:i,branch:false,delay:rnd()*.1});}
 for(let i=0;i<32;i++){const a=i/32*Math.PI*2+(rnd()-.5)*.1,r0=.22+rnd()*.17,r1=.8+rnd()*2.25,span=.08+rnd()*.14;blocks.push({a,r0,r1,span,lift:.08+rnd()*.48,drift:.05+rnd()*.25,tilt:(rnd()-.5)*.15,seed:i})}
 // engineered projected CAD network: access spine, compounds, units, panel lanes, trees, dimensions
 const add=(pts,delay=0,major=false)=>cad.push({pts:pts.map(([x,z])=>[x,.018,z]),delay,major});
 for(const off of [-.48,.48]){add([[0,0],[3.2,0],[3.2,4+off],[11,4+off],[11,12+off],[23,12+off]],0,true);add([[0,0],[-3.3,0],[-3.3,-4+off],[-17,-4+off],[-17,-13+off]],.08,true)}
 for(let side of [-1,1])for(let r=0;r<5;r++){const x=side*(6+r*3.4),z=(r%2?1:-1)*(5+r*1.25),ww=2.2+r*.15,hh=2.2+r*.35;add([[0,0],[x/2,0],[x/2,z],[x,z],[x+side*ww,z],[x+side*ww,z+hh],[x,z+hh],[x,z]],.1+r*.055);for(let j=0;j<3;j++)add([[x,z+.45+j*.65],[x+side*ww,z+.45+j*.65]],.16+r*.055)}
 for(let i=0;i<16;i++){let z=-13+i*1.16;add([[0,0],[2.2,-2],[2.2,z],[4.5,z],[4.5,z+1.02],[2.2,z+1.02],[2.2,z]],.15+i*.012)}
 for(let i=0;i<7;i++){const x=-18+i*6,z=15+Math.sin(i)*2.8,c=[];for(let j=0;j<=28;j++){const a=j/28*Math.PI*2;c.push([x+Math.cos(a)*1.1,z+Math.sin(a)*1.1])}add([[0,0],[x/2,8],[x,z],...c],.32+i*.02)}
 add([[-24,20],[25,20],[25,-21],[-24,-21],[-24,20]],.48,true);for(let i=0;i<11;i++){const x=-21+i*4.3;add([[x,20],[x,21.4],[x+.9,21.4]],.55+i*.01)}
 for(let i=0;i<65;i++)sparks.push({angle:rnd()*Math.PI*2,speed:1.3+rnd()*6.5,height:.8+rnd()*4.2,life:1.7+rnd()*1.5,seed:rnd()});
}
function camAt(t){if(mode==='welcome'){const drift=smooth(t/12);return camera([lerp(2.8,0,drift),lerp(5.9,5.2,drift),lerp(14.5,12.8,drift)],[0,.72,0],51)}
 if(t<4.2){const p=ease((t-.25)/3.95);return camera([0,1.72,7.9],[0,lerp(15,-.35,p),0],lerp(58,45,p))}
 if(t<7.4){const p=ease((t-4.2)/3.2);return camera([lerp(0,.65,p),lerp(.72,2.6,p),lerp(4.3,7.2,p)],[0,lerp(-.12,.05,p),0],lerp(52,47,p))}
 if(t<33){const p=ease((t-7.4)/25.6);return camera([lerp(.65,11.5,p),lerp(2.6,15.5,p),lerp(7.2,26,p)],[0,.03,0],47)}
 if(t<46){const p=ease((t-33)/13);return camera([lerp(11.5,0,p),lerp(15.5,5.3,p),lerp(26,12.5,p)],[0,.74,0],49)}
 return camera([0,5.3,12.5],[0,.74,0],49)}
function drawGround(cam,t){ctx.fillStyle='#020405';ctx.fillRect(0,0,w,h);const poly=[[-28,-.32,-30],[28,-.32,-30],[28,-.32,22],[-28,-.32,22]].map(p=>project(cam,p)).filter(Boolean);if(poly.length===4){const g=ctx.createLinearGradient(0,Math.min(...poly.map(p=>p.y)),0,h);g.addColorStop(0,'#07100f');g.addColorStop(.45,'#0b1213');g.addColorStop(1,'#030708');ctx.fillStyle=g;path(poly);ctx.fill();}
 // very subtle ground perspective guides to sell depth
 ctx.save();ctx.globalAlpha=mode==='sales'?.035:.025;ctx.strokeStyle='#9ab9aa';ctx.lineWidth=.6;for(let z=-22;z<=20;z+=4){const a=project(cam,[-28,-.305,z]),b=project(cam,[28,-.305,z]);if(a&&b){ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}ctx.restore();}
function circleProjected(cam,r,y=-.29,n=72){const ps=[];for(let i=0;i<=n;i++){const a=i/n*Math.PI*2,p=project(cam,[Math.cos(a)*r,y,Math.sin(a)*r]);if(p)ps.push(p)}return ps}
function roughCircleProjected(cam,r,y=-.29,phase=0,n=52){const ps=[];for(let i=0;i<=n;i++){const a=i/n*Math.PI*2,noise=1+.09*Math.sin(a*7+phase)+.045*Math.sin(a*13-phase*1.7),rr=r*noise,p=project(cam,[Math.cos(a)*rr,y,Math.sin(a)*rr]);if(p)ps.push(p)}return ps}
function drawCrater(cam,t,energy){const impact=mode==='sales'?4.2:0,active=mode==='sales'&&t>=impact,build=active?smooth((t-impact)/.48):1,rr=active?lerp(.16,.70,build):.26,c=roughCircleProjected(cam,rr,-.30,.8);if(c.length>2){ctx.save();ctx.fillStyle=active?'#000101':'#050a08';path(c);ctx.fill();const inner=roughCircleProjected(cam,rr*.72,-.305,2.1);if(inner.length>2){ctx.fillStyle='#000';path(inner);ctx.fill()}for(let pass=0;pass<3;pass++){ctx.strokeStyle=pass===0?`rgba(44,255,135,${.045*energy})`:pass===1?`rgba(66,240,144,${.15*energy})`:`rgba(172,255,207,${.32*energy})`;ctx.lineWidth=pass===0?13:pass===1?4:1;ctx.shadowColor='#37ff8b';ctx.shadowBlur=pass===0?24:pass===1?9:0;path(c);ctx.stroke()}ctx.shadowBlur=0;ctx.strokeStyle=`rgba(165,255,204,${.12*energy})`;ctx.lineWidth=.7;for(const phase of [1.4,2.7]){const rim=roughCircleProjected(cam,rr*(1.06+phase*.012),-.296,phase);path(rim);ctx.stroke()}ctx.restore();}}
function irregularProgress(t){const keys=[[4.6,0],[5.4,.07],[6.8,.12],[7.2,.2],[9,.25],[9.4,.32],[12,.39],[12.4,.47],[16,.55],[16.5,.63],[20,.69],[20.35,.76],[24,.82],[24.5,.89],[29,.94],[30.2,1]];if(t<=keys[0][0])return 0;for(let i=1;i<keys.length;i++)if(t<=keys[i][0]){const[a,x]=keys[i-1],[b,y]=keys[i];return lerp(x,y,smooth((t-a)/(b-a)))}return 1}
function crackProgress(t){if(mode!=='sales')return 0;if(t<33)return irregularProgress(t);if(t<37)return 1-ease((t-33)/4);return 0}
function partialPolyline(cam,pts,progress){if(progress<=0)return[];const segs=[];for(let i=1;i<pts.length;i++)segs.push(Math.hypot(pts[i][0]-pts[i-1][0],pts[i][2]-pts[i-1][2]));const total=segs.reduce((a,b)=>a+b,0)*progress;let left=total,out=[pts[0]];for(let i=1;i<pts.length&&left>0;i++){const d=segs[i-1];if(left>=d){out.push(pts[i]);left-=d}else{const q=left/d,a=pts[i-1],b=pts[i];out.push([lerp(a[0],b[0],q),lerp(a[1],b[1],q),lerp(a[2],b[2],q)]);left=0}}return out.map(p=>project(cam,p)).filter(Boolean)}
function pointAlong(ps,p){if(ps.length<2)return null;let lens=[],total=0;for(let i=1;i<ps.length;i++){const d=Math.hypot(ps[i].x-ps[i-1].x,ps[i].y-ps[i-1].y);lens.push(d);total+=d}let d=total*clamp(p);for(let i=1;i<ps.length;i++){if(d<=lens[i-1]){const q=d/(lens[i-1]||1);return{x:lerp(ps[i-1].x,ps[i].x,q),y:lerp(ps[i-1].y,ps[i].y,q)}}d-=lens[i-1]}return ps.at(-1)}
function drawCracks(cam,t){const base=crackProgress(t);if(base<=0)return;const retract=t>=33;for(const c of cracks){const p=clamp((base-c.delay)/(1-c.delay)),ps=partialPolyline(cam,c.pts,p);if(ps.length<2)continue;ctx.save();ctx.lineJoin='round';ctx.lineCap='round';const pulse=.55+.45*Math.sin(t*6.2+c.seed*.91); // fracture glow: wide diffuse energy + hot core
 ctx.strokeStyle=`rgba(21,255,122,${.028+.042*pulse})`;ctx.lineWidth=c.branch?7:12;ctx.shadowColor='#1fff77';ctx.shadowBlur=c.branch?18:28;path(ps);ctx.stroke();ctx.strokeStyle=`rgba(39,226,127,${.10+.10*pulse})`;ctx.lineWidth=c.branch?2.5:4.2;ctx.shadowBlur=8;path(ps);ctx.stroke();ctx.strokeStyle=`rgba(195,255,218,${.32+.38*pulse})`;ctx.lineWidth=c.branch?.55:.82;ctx.shadowBlur=2;path(ps);ctx.stroke();ctx.shadowBlur=0;
 // travelling energy packet follows the crack; reverses during collapse
 const travel=retract?1-((t*1.45+c.seed*.031)%1):((t*.82+c.seed*.019)%1);const bead=pointAlong(ps,travel);if(bead){const gr=ctx.createRadialGradient(bead.x,bead.y,0,bead.x,bead.y,c.branch?8:12);gr.addColorStop(0,'rgba(231,255,240,.9)');gr.addColorStop(.18,'rgba(93,255,163,.55)');gr.addColorStop(1,'rgba(45,255,137,0)');ctx.fillStyle=gr;ctx.beginPath();ctx.arc(bead.x,bead.y,c.branch?8:12,0,Math.PI*2);ctx.fill()}ctx.restore();}}
function drawBlocks(cam,t){if(mode!=='sales'||t<4.18||t>37.5)return;const f=irregularProgress(t),fall=clamp((t-5.2)/6),collapse=smooth((t-33)/4);for(const b of blocks){const q=clamp((f-(b.seed%8)*.012)/.72),dr=b.r1*(.25+.75*q)*(1-.22*collapse),lift=b.lift*Math.sin(Math.PI*clamp((t-4.2)/2.3))*(1-fall*.72)*(1-collapse),a=b.a+b.tilt*q;const pts=[[Math.cos(a-b.span)*b.r0,-.28+lift,Math.sin(a-b.span)*b.r0],[Math.cos(a-b.span)*dr,-.27+lift,Math.sin(a-b.span)*dr],[Math.cos(a+b.span)*dr,-.29+lift,Math.sin(a+b.span)*dr],[Math.cos(a+b.span)*b.r0,-.29+lift,Math.sin(a+b.span)*b.r0]].map(p=>project(cam,p)).filter(Boolean);if(pts.length===4){ctx.fillStyle=`rgba(${6+b.seed%5},${12+b.seed%8},${9+b.seed%5},${.9-collapse*.65})`;path(pts);ctx.fill();ctx.strokeStyle=`rgba(96,255,162,${.05*q*(1-collapse)})`;ctx.lineWidth=.7;ctx.stroke()}}}
function drawImpactDebris(cam,t){if(mode!=='sales')return;const v=t-4.2;if(v<0||v>3.1)return;ctx.save();for(const s of sparks){if(v>s.life)continue;const dist=v*s.speed,px=[Math.cos(s.angle)*dist,-.05+s.height*v-2.3*v*v,Math.sin(s.angle)*dist],p=project(cam,px);if(!p)continue;const a=(1-v/s.life)*.55;ctx.fillStyle=`rgba(137,255,186,${a})`;ctx.fillRect(p.x,p.y,Math.max(1,p.scale*.012),Math.max(1,p.scale*.012))}ctx.restore()}
function cadProgress(t){if(mode==='welcome'){if(t<3.0)return 0;if(t<8.0)return ease((t-3)/5);if(t<8.45)return 1;if(t<10.15)return 1-ease((t-8.45)/1.7);return 0}if(t<70)return 0;if(t<76)return ease((t-70)/6);if(t<78.2)return 1;return 1-smooth((t-78.2)/1.4)}
function drawCad(cam,t){const p=cadProgress(t);if(p<=0)return;const active=cad.length*p;for(let i=0;i<Math.ceil(active);i++){const c=cad[i],local=clamp(active-i),ps=c.pts.map(x=>project(cam,x)).filter(Boolean);if(ps.length<2)continue;ctx.save();ctx.lineJoin='miter';ctx.lineCap='square';ctx.strokeStyle=c.major?`rgba(113,255,174,${.42+.4*local})`:`rgba(54,224,132,${.25+.42*local})`;ctx.lineWidth=c.major?1.35:.65;ctx.shadowColor='#35ff8b';ctx.shadowBlur=c.major?6:2;path(ps);ctx.stroke();ctx.shadowBlur=0;const head=pointAlong(ps,local);if(head&&i===Math.floor(active)){const g=ctx.createRadialGradient(head.x,head.y,0,head.x,head.y,11);g.addColorStop(0,'rgba(235,255,243,.9)');g.addColorStop(.22,'rgba(74,255,151,.48)');g.addColorStop(1,'rgba(74,255,151,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(head.x,head.y,11,0,Math.PI*2);ctx.fill()}ctx.restore()}}
function drawPinShape(x,y,size,charge=0,alpha=1){ctx.save();ctx.translate(x,y);ctx.globalAlpha=alpha;const grad=ctx.createLinearGradient(-size*.45,-size*.55,size*.42,size*.75);grad.addColorStop(0,charge>.5?'#a3f0bd':'#73877d');grad.addColorStop(.46,charge>.3?'#63c991':'#586a61');grad.addColorStop(1,'#26352e');ctx.fillStyle=grad;ctx.shadowColor='#43ff91';ctx.shadowBlur=4+charge*22;ctx.beginPath();ctx.moveTo(0,size*.78);ctx.bezierCurveTo(-size*.52,size*.18,-size*.49,-size*.46,0,-size*.58);ctx.bezierCurveTo(size*.49,-size*.46,size*.52,size*.18,0,size*.78);ctx.fill();ctx.shadowBlur=0;ctx.lineWidth=Math.max(1,size*.02);ctx.strokeStyle='rgba(222,239,229,.52)';ctx.stroke();ctx.fillStyle='#07100c';ctx.beginPath();ctx.arc(0,-size*.18,size*.17,0,Math.PI*2);ctx.fill();ctx.strokeStyle=`rgba(151,255,191,${.3+charge*.55})`;ctx.lineWidth=Math.max(1,size*.025);ctx.stroke();ctx.restore()}
function logoTarget(){const r=wordmarkStage?.getBoundingClientRect();return r?{x:r.left+r.width*.4115,y:r.top+r.height*.831}:null}
function drawPin(cam,t){let pos,charge=.08,alpha=1,size=46;if(mode==='welcome'){
 let y=.85;if(t<2.8){charge=.08+.12*Math.sin(t*17)**8+.25*Math.sin(t*4.1)**18;y=.85+Math.sin(t*43)*.006*smooth(t/2.8)}else if(t<9.6){charge=.48+.16*Math.sin(t*5.4);y=.85}else if(t<11.0){charge=.65;y=lerp(.85,1.55,ease((t-9.6)/1.4))}else{y=1.55;charge=.7}pos=project(cam,[0,y,0]);if(t>10.7){const target=logoTarget();if(target&&pos){const q=ease((t-10.7)/1.45);pos={x:lerp(pos.x,target.x,q),y:lerp(pos.y,target.y,q),scale:pos.scale};size=lerp(clamp(pos.scale*.64,24,74),18,q);alpha=1-smooth((t-12.0)/.55)}}}
 else{if(t<4.2){const p=clamp((t-.25)/3.95);pos=project(cam,[0,lerp(15,-.55,p*p),0]);charge=.08+.1*p;size=pos?clamp(pos.scale*.66,18,90):46}else if(t<43){pos=project(cam,[0,-.22,0]);charge=t<37?.52+.16*Math.sin(t*5):.025}else if(t<47.5){const q=ease((t-43)/4.5);pos=project(cam,[0,lerp(-.22,1.45,q),0]);charge=.2+.65*q}else{pos=project(cam,[0,1.45,0]);charge=.68}if(t>70){const target=logoTarget();if(target&&pos){const q=ease((t-70)/4.2);pos={x:lerp(pos.x,target.x,q),y:lerp(pos.y,target.y,q),scale:pos.scale};size=lerp(clamp(pos.scale*.66,22,80),18,q);alpha=1-smooth((t-74)/.65)}}}
 if(pos)drawPinShape(pos.x,pos.y,size||clamp(pos.scale*.66,22,80),charge,alpha);return charge}
function flash(t){const xs=mode==='welcome'?[2.8,8.25]:[4.2,35.3,46.0,77.0];let a=0;for(const x of xs){const d=Math.abs(t-x);if(d<.22)a=Math.max(a,(1-d/.22)*(x===4.2?.64:.34))}if(a){ctx.fillStyle=`rgba(203,255,224,${a})`;ctx.fillRect(0,0,w,h)}}
function drawPulse(cam,t){const center=project(cam,[0,-.29,0]);if(!center)return;let energy=mode==='welcome'?(.25+.18*Math.sin(t*4.5)**2):(t>4.2&&t<37?.35+.25*Math.sin(t*5.5)**2:t>43?.22:0);if(energy<=0)return;const r=80+energy*130,g=ctx.createRadialGradient(center.x,center.y,0,center.x,center.y,r);g.addColorStop(0,`rgba(54,255,140,${.10*energy})`);g.addColorStop(.28,`rgba(40,232,124,${.055*energy})`);g.addColorStop(1,'rgba(30,200,110,0)');ctx.fillStyle=g;ctx.fillRect(center.x-r,center.y-r,r*2,r*2)}
function processWords(t){if(mode!=='sales')return;const rel=t-8;[...words.querySelectorAll('.process-word')].forEach((el,i)=>{const at=+el.dataset.start,d=+el.dataset.duration,p=rel-at,o=smooth(p/.55)*(1-smooth((p-d)/.8));el.style.opacity=String(t<33?o:0);el.style.transform=`translate(-50%,calc(-50% + ${lerp(12,-8,clamp(p/(d+1)))}px))`});[...words.querySelectorAll('.process-data')].forEach((el,i)=>{const p=rel-i*.08,o=smooth(p/1.6)*(.05+.1*Math.sin(i*7.7+t*1.8)**2)*(1-smooth((t-33)/2));el.style.opacity=String(Math.max(0,o))})}
function prepareWords(){words.replaceChildren();let at=0;PROCESS.forEach((text,i)=>{const el=document.createElement('div');el.className='process-word';el.textContent=text;el.style.setProperty('--x',(17+(i*31)%66)+'%');el.style.setProperty('--y',(23+(i*17)%50)+'%');el.dataset.start=at;el.dataset.duration=1.0+(i%4)*.22;at+=.82+(i%3)*.12;words.append(el)});for(let i=0;i<125;i++){const el=document.createElement('div');el.className='process-data';el.textContent=PROCESS[i%PROCESS.length]+' / '+String((i*314159)%100000).padStart(5,'0');el.style.setProperty('--x',(3+(i*43)%91)+'%');el.style.setProperty('--y',(9+(i*19)%82)+'%');words.append(el)}}
function setSentence(text,opacity){if(sentence.dataset.text!==text){sentence.innerHTML='';sentence.textContent=text;sentence.dataset.text=text}sentence.style.opacity=String(opacity)}
function propositions(t){if(mode!=='sales')return;if(t<40){setSentence('',0);return}const items=[[40,45,'WHAT IF THERE WAS A BETTER WAY?'],[46,49.6,'ONE SOURCE OF INFORMATION'],[50,53.6,'ONE TEAM'],[54,57.6,'ONE TOOL'],[58,63,'IT’S TIME TO WORK SMARTER'],[64,67.2,'IT’S TIME TO ASK']];const x=items.find(([a,b])=>t>=a&&t<b);if(x){const[a,b,text]=x;setSentence(text,smooth((t-a)/.6)*(1-smooth((t-b+.5)/.5)))}else if(t<67)setSentence('',0);if(t>=66.8&&t<75)letterMorph(t)}
function letterMorph(t){if(!sentence.querySelector('span')){sentence.innerHTML=[...'IT’S TIME TO ASK'].map((c,i)=>`<span data-index="${i}">${c===' '?'&nbsp;':c}</span>`).join('');sentence.dataset.text='__morph__'}const selected=[3,13,7,6],centres=[.153,.413,.724,.942],r=wordmarkStage.getBoundingClientRect();sentence.style.opacity='1';const p=ease((t-68.2)/4.8);sentence.querySelectorAll('span').forEach((el,i)=>{const n=selected.indexOf(i);if(n<0){el.style.opacity=String(1-smooth((t-67.1)/1.1));return}el.classList.add('charged');if(!el.dataset.x){const b=el.getBoundingClientRect();el.dataset.x=b.left+b.width/2;el.dataset.y=b.top+b.height/2}const tx=r.left+r.width*centres[n],ty=r.top+r.height*.52;el.style.transform=`translate(${(tx-+el.dataset.x)*p}px,${(ty-+el.dataset.y)*p}px) scale(${lerp(1,.78,p)})`;el.style.opacity=String(1-smooth((t-73.2)/1.2))})}
function brandProgress(t){const base=mode==='welcome'?11.65:74.0,p=smooth((t-base)/1.25);logo.style.opacity=String(p);logo.style.clipPath=`inset(${(1-p)*100}% 0 0 0)`;const svg=$('.logo-edge-pass'),q=clamp((t-base-1.3)/1.6);svg.style.opacity=q>0&&q<1?'1':'0';svg.querySelectorAll('path').forEach(p=>p.style.strokeDashoffset=String(5-q*105));const ready=smooth((t-base-3.0)/.75);welcomeUI.style.opacity=String(ready);root.classList.toggle('ready',ready>.95);if(ready>.98&&mode==='welcome')finishAtWelcome()}
function cameraFor(t){return camAt(t)}
function frame(now){if(!running)return;const t=(now-start)/1000,cam=cameraFor(t);drawGround(cam,t);drawBlocks(cam,t);drawCrater(cam,t,mode==='sales'?crackProgress(t):cadProgress(t));drawCracks(cam,t);drawImpactDebris(cam,t);drawCad(cam,t);drawPulse(cam,t);drawPin(cam,t);flash(t);processWords(t);propositions(t);brandProgress(t);if((mode==='welcome'&&t<15.6)||(mode==='sales'&&t<81.5))raf=requestAnimationFrame(frame);else finishAtWelcome()}
function drawStill(){if(!ctx)return;const cam=camera([0,5.2,12.5],[0,.75,0],49);drawGround(cam,0);drawPin(cam,mode==='welcome'?12:76)}
function resetVisual(){cancelAnimationFrame(raf);running=false;words.replaceChildren();sentence.innerHTML='';sentence.dataset.text='';sentence.style.opacity='0';logo.style.opacity='0';logo.style.clipPath='inset(100% 0 0 0)';welcomeUI.style.opacity='0';$('.logo-edge-pass').style.opacity='0';root.classList.remove('ready');$('#cinemaClosed').hidden=true}
function playAudio(which){welcomeAudio.pause();salesAudio.pause();const a=which==='sales'?salesAudio:welcomeAudio;a.currentTime=0;a.muted=!sound;a.volume=which==='sales'?.78:.88;a.play().catch(()=>{if(sound){status.textContent='Cinematic sound could not start. Tap Sound to retry.'}})}
function stopNarration(){}
function play(which='welcome'){prepareGeometry();resetVisual();mode=which;root.hidden=false;$('#app').inert=true;$('#app').setAttribute('aria-hidden','true');gate.classList.add('dismissed');$('#launchSkip').hidden=false;$('#launchSoundBtn').hidden=false;$('#launchSkip').textContent=which==='sales'?'Back to welcome':'Skip intro';start=performance.now();running=true;if(which==='sales')prepareWords();playAudio(which);raf=requestAnimationFrame(frame)}
function finishAtWelcome(){cancelAnimationFrame(raf);running=false;welcomeAudio.pause();salesAudio.pause();words.replaceChildren();sentence.innerHTML='';sentence.style.opacity='0';logo.style.opacity='1';logo.style.clipPath='inset(0 0 0 0)';welcomeUI.style.opacity='1';$('.logo-edge-pass').style.opacity='0';root.classList.add('ready');$('#launchSkip').textContent='Enter workspace';drawStill()}
async function enter(){resetVisual();welcomeAudio.pause();salesAudio.pause();root.hidden=true;$('#app').inert=false;$('#app').setAttribute('aria-hidden','false');await window.SAMIWorkspace?.ready;if(localStorage.getItem('sami.tutorial.seen')!=='yes')window.SAMIWorkspace?.runAction('tutorial')}
async function startWithSound(){sound=true;$('#launchSoundBtn').textContent='Sound on';status.textContent='Cinematic sound and narration enabled';play(location.hash==='#why'?'sales':'welcome')}
async function shutdown(){resetVisual();root.hidden=false;$('#app').inert=true;$('#app').setAttribute('aria-hidden','true');gate.classList.add('dismissed');$('#launchSkip').hidden=true;$('#launchSoundBtn').hidden=true;logo.style.opacity='1';logo.style.clipPath='inset(0 0 0 0)';await logo.animate([{opacity:1,filter:'brightness(1)'},{opacity:.5,filter:'brightness(1.5)',offset:.38},{opacity:0,filter:'brightness(.25)'}],{duration:1800,easing:'cubic-bezier(.4,0,.2,1)',fill:'forwards'}).finished.catch(()=>{});logo.style.opacity='0';$('#cinemaClosed').hidden=false}
$('#startSound').onclick=startWithSound;$('#startQuiet').onclick=()=>{sound=false;$('#launchSoundBtn').textContent='Sound off';play(location.hash==='#why'?'sales':'welcome')};$('#launchSkip').onclick=()=>root.classList.contains('ready')?enter():finishAtWelcome();$('#launchSoundBtn').onclick=async()=>{sound=!sound;$('#launchSoundBtn').textContent=sound?'Sound on':'Sound off';const a=mode==='sales'?salesAudio:welcomeAudio;a.muted=!sound;};$('#enterSami').onclick=enter;$('#whySami').onclick=()=>play('sales');$('#reopenSami').onclick=()=>{gate.classList.remove('dismissed');$('#cinemaClosed').hidden=true;logo.style.opacity='0';welcomeUI.style.opacity='0';$('#launchSkip').hidden=true;$('#launchSoundBtn').hidden=true};
window.SAMICinema={play,shutdown,enter};addEventListener('resize',resize,{passive:true});document.addEventListener('visibilitychange',()=>{if(document.hidden&&running){suspendedAt=performance.now();cancelAnimationFrame(raf);welcomeAudio.pause();salesAudio.pause();}else if(suspendedAt&&running){start+=performance.now()-suspendedAt;suspendedAt=0;const a=mode==='sales'?salesAudio:welcomeAudio;a.currentTime=(performance.now()-start)/1000;a.play().catch(()=>{});raf=requestAnimationFrame(frame)}});
prepareGeometry();resize();if(document.documentElement.classList.contains('install-required'))root.hidden=true;else{root.hidden=false;$('#app').inert=true;$('#app').setAttribute('aria-hidden','true');$('#launchSkip').hidden=true;$('#launchSoundBtn').hidden=true;}
})();
